# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and  Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
   pre_build:
    - python3 tools/doc/gen_docker_images_table.py -o .docs/docker_images_table.rst
    - python3 tools/doc/gen_nuget_table.py -o .docs/nuget_packages_table.rst
    - python3 tools/doc/gen_npm_table.py -o .docs/npm_packages_table.rst
    - python3 tools/doc/gen_crates_table.py -o .docs/crates_table.rst

# Move anchors out of the titles
# Build documentation in the ".docs/" directory with Sphinx
sphinx:
   configuration: .docs/conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: .docs/requirements.txt
        
