FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim

RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

ENV ARMONIK_DEBUG_WAIT_TASK=90
ENV ARMONIK_DEBUG_WAIT_CLIENT=90

COPY . /app/publish
WORKDIR /app/publish

ENTRYPOINT ["dotnet"]