export ARMONIK_PROFILE="default"
export ARMONIK_REGION="eu-west-3"
export ARMONIK_SUFFIX="main"
export ARMONIK_BUCKET_NAME="armonik-tfstate"
export ARMONIK_KUBERNETES_NAMESPACE="armonik"
export KEDA_KUBERNETES_NAMESPACE="default"
export METRICS_SERVER_KUBERNETES_NAMESPACE="kube-system"
