#cloud-config

merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

locale: en_US.UTF-8

write_files:
  - content: |
      rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
      yum install -y dotnet-sdk-6.0 dotnet-runtime-6.0
    path: /app/install-dotnet.sh
    permissions: 0755
    owner: root

runcmd:
  - bash /app/install-dotnet.sh