#cloud-config

merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

locale: en_US.UTF-8

write_files:
  - content: |
      #amazon-linux-extras enable python3.7
      #yum install -y python3.7
      update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1
      curl -O https://bootstrap.pypa.io/get-pip.py
      python3 get-pip.py --user
      echo "PATH=~/.local/bin:$PATH" >> /home/ec2-user/.bashrc
      source /home/ec2-user/.bashrc
      python -m pip install python-hcl2
      python -m pip install jsonpath-ng
    path: /app/install-python3.sh
    permissions: 0755
    owner: root

runcmd:
  - bash /app/install-python3.sh