apiVersion: batch/v1
kind: Job
metadata:
  name: bench-session
  namespace: armonik
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: bench-session
          image: dockerhubaneo/armonik_core_bench_test_client:0.28.0
          env:
            - name: BenchOptions__NTasks
              value: "1000000"
            - name: BenchOptions__Partition
              value: bench
            - name: BenchOptions__Options__SessionName
              value: benchmark
            - name: BenchOptions__PurgeData
              value: "false"
            - name: BenchOptions__DownloadResults
              value: "false"
            - name: BenchOptions__PayloadSize
              value: "1"
            - name: BenchOptions__ResultSize
              value: "1"
            - name: BenchOptions__DegreeOfParallelism
              value: "10"
            - name: BenchOptions__PauseSessionDuringSubmission
              value: "true"
            - name: BenchOptions__TaskDurationMs
              value: "0"
            - name: GrpcClient__Endpoint
              value: "" 
          resources:
            requests:
              memory: "500Mi"
              cpu: "1"

