apiVersion: batch/v1
kind: Job
metadata:
  name: bench-session
  namespace: armonik
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: bench-session
          image: dockerhubaneo/armonik_core_bench_test_client:0.31.2 # version should at least be 0.27.4
          env:
            - name: BenchOptions__NTasks
              value: "50000"
            - name: BenchOptions__Partition
              value: bench
            - name: BenchOptions__Options__SessionName
              value: "my-session"
            - name: BenchOptions__PayloadSize
              value: "1"
            - name: BenchOptions__ResultSize
              value: "1"
            - name: BenchOptions__TaskDurationMs
              value: "0"
            - name: BenchOptions__DegreeOfParallelism
              value: "10"
            - name: BenchOptions__PauseSessionDuringSubmission
              value: "true"
            - name: BenchOptions__PurgeData
              value: "false"
            - name: BenchOptions__DownloadResults
              value: "false"
            - name: GrpcClient__Endpoint
              value: http://:5001
          resources:
            requests:
              cpu: "1"
              memory: "500Mi"
