apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mongoshclient
  name: mongoshclient
  namespace: armonik
spec:
  containers:
  - name: mongosh
    image: rtsp/mongosh
    command: ["tail", "-f"]
    args: ["/dev/null"]
#    command: [mongosh]
#    args: ["--tlsCAFile /mongodb/chain.pem","--tlsAllowInvalidCertificates", "--tlsAllowInvalidHostnames", "--tls", "-u $MONGO_INITDB_ROOT_USERNAME", "-p $MONGO_INITDB_ROOT_PASSWORD", "mongodb://mongodb:27017"]
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongodb-admin
          key: username
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-admin
          key: password
    volumeMounts:
    - name: mongodb-secret-volume
      mountPath: /mongodb/
    resources: {}
  volumes:
  - name: mongodb-secret-volume
    secret:
      secretName: mongodb
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
