name: "Destroy AWS"

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Prefix for the deployment"
        required: false
        default: "armonik-cicd"
  push:

jobs:
  destroy:
    name: "Destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: aneoconsulting/ArmoniK.Action.Deploy/dependencies@fl/test
        with:
          aws: true
          terraform: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: destroy
        name: Destroy deployment
        uses: aneoconsulting/ArmoniK.Action.Deploy/destroy@fl/test
        with:
          type: aws
          prefix: ${{ inputs.prefix }}
