name: Validate Docs Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - run: npm install -g pnpm@^9.0.2

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: ".docs/pnpm-lock.yaml"

      - name: Install dependencies
        run: cd .docs && pnpm i

      - name: Use NODE_ENV=production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Static HTML export with Nuxt
        run: cd .docs && pnpm generate

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - run: npm install -g pnpm@^9.0.2

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: ".docs/pnpm-lock.yaml"

      - run: cd .docs && pnpm i
      
      - run: cd .docs && pnpm lint:md

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - run: npm install -g pnpm@^9.0.2

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: ".docs/pnpm-lock.yaml"

      - run: cd .docs && pnpm i
      
      - run: cd .docs && pnpm lint
