name: Validate Docs Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - run: npm i -g pnpm @antfu/ni

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: ".docs/pnpm-lock.yaml"

      - name: Install dependencies
        run: cd .docs && nci

      - name: Use NODE_ENV=production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Static HTML export with Nuxt
        run: cd .docs && nr generate

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - run: npm i -g pnpm @antfu/ni

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: ".docs/pnpm-lock.yaml"

      - run: cd .docs && nci
      
      - run: cd .docs && nr lint:md

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - run: npm i -g pnpm @antfu/ni

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: ".docs/pnpm-lock.yaml"

      - run: cd .docs && nci
      
      - run: cd .docs && nr lint
